// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRR_b6HC3Yi0esMHZ5lIwZB5y2x1hzmQ4',
    appId: '1:356185833612:web:ff37f646b9761ac2b83ba9',
    messagingSenderId: '356185833612',
    projectId: 'flutter-firebase-4322e',
    authDomain: 'flutter-firebase-4322e.firebaseapp.com',
    storageBucket: 'flutter-firebase-4322e.appspot.com',
    measurementId: 'G-8EQ54R4XQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmjoimzAunp4dVeHfu1Oc4HLexexCmrlA',
    appId: '1:356185833612:android:972cca6d1ff0d60fb83ba9',
    messagingSenderId: '356185833612',
    projectId: 'flutter-firebase-4322e',
    storageBucket: 'flutter-firebase-4322e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9EQ1EAaZcA-EZsboBgmvJ5XXWZY4WmtI',
    appId: '1:356185833612:ios:13effc4e1df2f21ab83ba9',
    messagingSenderId: '356185833612',
    projectId: 'flutter-firebase-4322e',
    storageBucket: 'flutter-firebase-4322e.appspot.com',
    iosClientId: '356185833612-7lbifqd1qqjpfhvu8d6ogt12p3dj5g06.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9EQ1EAaZcA-EZsboBgmvJ5XXWZY4WmtI',
    appId: '1:356185833612:ios:13effc4e1df2f21ab83ba9',
    messagingSenderId: '356185833612',
    projectId: 'flutter-firebase-4322e',
    storageBucket: 'flutter-firebase-4322e.appspot.com',
    iosClientId: '356185833612-7lbifqd1qqjpfhvu8d6ogt12p3dj5g06.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );
}
